hospital_ms/department_doctors_app/urls.py
from django.urls import path

from department_doctors_app import views


app_name = 'department_doctors_app'

urlpatterns = [
    path('departmentlist/', views.DepartmentListView.as_view(), name='departmentlist'),
    path('create/', views.DepartmentCreateView.as_view(), name='createdepartment'),
    path('update/<int:pk>/', views.DepartmentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.DepartmentDeleteView.as_view(), name='delete'),

     path('createdoctor/', views.DoctorCreateView.as_view(), name='createdoctor'),
     path('doctorlist/', views.DoctorsListView.as_view(), name='doctor_list'),
     path('doctordetail/<int:pk>/',views.DoctorDetailView.as_view(), name='doctor_detail'),


]

hospital_ms/hospital_app/urls.py
from django.urls import path

from hospital_app import views


app_name = 'hospital_app'

urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('booking/',views.AppointmentFormView.as_view(),name='booking'),


    path('appointmentlist1', views.AppointmentListView1.as_view(), name='list1'),
    path('appointmentlist2', views.AppointmentListView2.as_view(), name='list2'),
    path('appointmentlist3', views.AppointmentListView3.as_view(), name='list3'),
    path('appointmentlistpatients', views.AppointmentViewListForPatients.as_view(), name='list4'),

    path('update_status/<int:appointment_id>/', views.AppointmentStatusUpdateView.as_view(), name='update_status'),

    path('appointmenthistory/<int:pk>/', views.AppointmentHistoryView.as_view(), name='ahistory'),

    path('timeslot/', views.TimeSlotCreateView.as_view(), name='add_timeslot'),
    path('createadmin', views.AdminCreateView.as_view(), name='create'),




    path('user-signup/', views.UserSignupView.as_view(), name='usersignup'),
    path('superuser-signup/', views.SuperAdminSignupView.as_view(), name='superadminsign'),

    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    ]

hospital_ms/hospital_ms/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hospital_app.urls')),
    path('departmentlist/',include('department_doctors_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root = settings.MEDIA_ROOT)

hospital_ms/hospital_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from department_doctors_app.models import Doctors



class CustomUser(AbstractUser):
    USER_TYPE_CHOICES = (
        ('superadmin', 'Super Admin'),
        ('admin', 'Admin'),
        ('user', 'User'),
    )

    user_type = models.CharField(max_length=100, choices=USER_TYPE_CHOICES, default='user')
    user_access = models.OneToOneField('UserAccess', related_name='useracc', on_delete=models.CASCADE, null=True,
                                       blank=True)
    def __str__(self):
        return self.user_type

User = get_user_model()

class UserAccess(models.Model):
    user = models.OneToOneField(CustomUser, related_name='uaccess', on_delete=models.CASCADE, null=True, blank=True)
    can_edit = models.BooleanField(default=False)
    can_view = models.BooleanField(default=False)
    def __str__(self):
        return str(self.user)


class Appointment(models.Model):
    TokenNo = models.AutoField(primary_key=True, unique=True)
    patient_name = models.CharField( max_length=100,blank=False, null=False)
    patient_place = models.CharField(max_length=100, blank=False, null=False)
    patient_phone = models.CharField(max_length=100, blank=False, null=False)
    patient_email = models.EmailField(max_length=255, blank=False)
    appointment_date = models.DateTimeField()
    appointment_time = models.ForeignKey('TimeSlot', on_delete=models.CASCADE, unique_for_date='appointment_date')
    doctor = models.ForeignKey(Doctors, on_delete=models.CASCADE)
    patient_department = models.CharField(max_length=200, choices=[('ortho', 'orthopedics'), ('cardio', 'Cardiology'),
                                                                   ('derma', 'Dermatology'), ('Gynec', 'Gynecology'), ])
    status = models.CharField(max_length=50, choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'),
                                                      ('rejected', 'Rejected')])
    history = models.ManyToManyField('History', blank=True, related_name='appointments')

    def __str__(self):
        return str(self.TokenNo)


class History(models.Model):
    date = models.DateField()
    time = models.TimeField()
    admin = models.CharField(max_length=255)
    appointment = models.ForeignKey('Appointment', on_delete=models.CASCADE, related_name='history_entries')

    def __str__(self):
        return self.admin



class TimeSlot(models.Model):
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return f" ({self.start_time} - {self.end_time})"

hospital_ms/templates/appointment_history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>History Detail</title>
</head>
<body>
    <h1>History Detail</h1>
    <p>Date: {{ history.date }}</p>
    <p>Time: {{ history.time }}</p>
    <p>Admin: {{ history.admin }}</p>
    <p>Appointment ID: {{ history.appointment_id }}</p>

    <!-- You can add more details as needed -->

    <a href="{% url 'list1' %}">Back to List</a>
</body>
</html>

hospital_ms/templates/appointment_list_view_users.html
{% extends 'base.html' %}

{% block content %}
  <h1>Appointment List with status For Patients </h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Place</th>
            <th>Consulting Doctor</th>
            <th>Department</th>
            <th>Date</th>
            <th>Time Slot</th>
            <th>Status</th>

        </tr>
    </thead>
    <tbody>
        {% for i in appointments %}
        <tr>
            <td>{{ i.patient_name }}</td>
            <td>{{ i.patient_email }}</td>
            <td>{{ i.patient_phone }}</td>
            <td>{{ i.patient_place }}</td>
            <td>{{ i.doctor }}</td>
            <td>{{ i.patient_department }}</td>
            <td>{{ i.appointment_date }}</td>
            <td>{{ i.appointment_time }}</td>
            <td>{{ i.get_status_display }}</td>

        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

hospital_ms/templates/booking.html
{% extends 'base.html' %}

{% block content %}
  <h1>bookings</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

hospital_ms/templates/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>Create Admin</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
{% endblock %}

hospital_ms/templates/create_department.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

hospital_ms/templates/delete_department.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Department</h1>
  <p>Are you sure you want to delete the Department "{{object.department_name }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
    <a href="{% url 'department_doctors_app:departmentlist' %}">Cancel</a>
  </form>
{% endblock %}

hospital_ms/templates/department_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <center>
        <h1>Department list</h1>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Department Name</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                {% for i in departmentList %}
                <tr>
                    <td>{{ i.department_name }}</td>
                    <td>{{ i.department_description }}</td>
                    {% if user.user_type in 'Admin Super Admin' %}
                         <td>
                                <a class="nav-link" href="{% url 'department_doctors_app:update' i.pk %}"><h3>Edit</h3></a>
                         </td>
                         <td>
                                <a class="nav-link" href="{% url 'department_doctors_app:delete' i.pk %}"><h3>Delete</h3></a>
                         </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if user.user_type == 'Super Admin' %}
          <button class="nav-link btn btn-danger" onclick="location.href='{% url 'department_doctors_app:createdepartment' %}'">Create Department</button>
        {% endif %}
    </center>
</div>
{% endblock %}

hospital_ms/templates/doctors_detail.html
{% extends 'base.html' %}

{% block content %}
<center>
  <h1>Vehicle Detail</h1>
  <p><strong>Doctor Name:</strong> {{ doctorr.doctor_name }}</p>
  <p><strong>Doctor Department:</strong> {{ doctorr.doctor_department }}</p>
  <p><strong>Doctor's Qualification:</strong> {{ doctorr.qualification }}</p>
  <p><strong>Doctors Image:</strong>
    <img src="{{ doctorr.photo.url }}"  alt="{{ doctorr.doctor_name }}'s photo" style="max-width: 300px; max-height: 300px";>
  </p>
</center>
{% endblock %}

hospital_ms/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

hospital_ms/templates/update_department.html
{% extends 'base.html' %}

{% block content %}
  <h1>Update Department</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>
{% endblock %}

hospital_ms/templates/user_register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2>User Signup</h2>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit">
    </form>
</div>
{% endblock %}

hospital_ms/templates/view1.html
{% extends 'base.html' %}

{% block content %}
           <ul class="nav-item">
                <a class="nav-link" href="{% url 'hospital_app:create' %}">create Admin</a>

                <a class="nav-link" href="{% url 'hospital_app:add_timeslot' %}">Add time slot</a>

                <a class="nav-link" href="{% url 'department_doctors_app:createdoctor' %}">create doctor</a>
            </ul>
  <h1>Appointment List with status and History For Super Admin</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Place</th>
            <th>Consulting Doctor</th>
            <th>Department</th>
            <th>Date</th>
            <th>Time Slot</th>
            <th>Status</th>
            <th>History</th>
        </tr>
    </thead>
    <tbody>
        {% for i in appointments %}
        <tr>
            <td>{{ i.patient_name }}</td>
            <td>{{ i.patient_email }}</td>
            <td>{{ i.patient_phone }}</td>
            <td>{{ i.patient_place }}</td>
            <td>{{ i.doctor }}</td>
            <td>{{ i.patient_department }}</td>
            <td>{{ i.appointment_date }}</td>
            <td>{{ i.appointment_time }}</td>
            <td>{{ i.status }}</td>
            <td>
                <form method="post" action="{% url 'hospital_app:update_status' i.pk %}">
                  {% csrf_token %}
                  {{ form }}
                  <button type="submit">Update Status</button>
                </form>

            </td>
            <td><a href="{% url 'hospital_app:ahistory' i.pk %}">History</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

hospital_ms/templates/view2.html
{% extends 'base.html' %}

{% block content %}
  <h1>Appointment List with status For Staffs </h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Place</th>
            <th>Consulting Doctor</th>
            <th>Department</th>
            <th>Date</th>
            <th>Time Slot</th>
            <th>Status</th>

        </tr>
    </thead>
    <tbody>
        {% for i in appointments %}
        <tr>
            <td>{{ i.patient_name }}</td>
            <td>{{ i.patient_email }}</td>
            <td>{{ i.patient_phone }}</td>
            <td>{{ i.patient_place }}</td>
            <td>{{ i.doctor }}</td>
            <td>{{ i.patient_department }}</td>
            <td>{{ i.appointment_date }}</td>
            <td>{{ i.appointment_time }}</td>
            <td>
                <form method="post" action="{% url 'update_status' i.pk %}">
                        {% csrf_token %}
                        <select name="status">
                            <option value="approved">Approved</option>
                            <option value="rejected">Rejected</option>
                            <option value="pending">Pending</option>
                        </select>
                        <button type="submit">Update Status</button>
                </form>

            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

hospital_ms/templates/view3.html
{% extends 'base.html' %}

{% block content %}
<center>
    <h1><i>Welcome</i></h1>
  <h3>Please book your Appointments here</h3>

    <a class="nav-link" href="{% url 'hospital_app:booking' %}">
        <button class="btn btn-primary">Appointment Booking</button>
    </a>

    <a class="nav-link" href="{% url 'hospital_app:list4' %}">
        <button class="btn btn-primary">View Appointments List</button>
    </a>

{% endblock %}